---
grails:
    profile: web
    codegen:
        defaultPackage: vincool
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

vincool:
  instructorDomain: "@nearsoft.com"
---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

---
jodatime:
  format:
    html5: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

dataSource:
    pooled: true
    jmxExport: true

environments:
    development:
        dataSource:
            dbCreate: none
            url: jdbc:postgresql://localhost:5432/vincool
            username: vincool
            password: vincool
            driverClassName: org.postgresql.Driver
            dialect: org.hibernate.dialect.PostgreSQLDialect
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

    test:
        dataSource:
            dbCreate: none
            url: jdbc:postgresql://localhost:5432/vincool
            username: vincool
            password: vincool
            driverClassName: org.postgresql.Driver
            dialect: org.hibernate.dialect.PostgreSQLDialect

    production:
        dataSource:
            dbCreate: none
            dialect: org.hibernate.dialect.PostgreSQLDialect
            driverClassName: org.postgresql.Driver
            url: jdbc:postgresql://localhost:5432/vincool?sslmode=require
            username: postgres
            password: postgres

            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

grails:
    serverURL: ${grails.serverurl:http://localhost:8080}
    plugin:
        springsecurity:
            auth:
              loginFormUrl: '/login'
            oauth2:
                active: true
                registration:
                    askToLinkOrCreateAccountUri: '/login/signin'
                    roleNames: ['ROLE_STUDENT','ROLE_ADMIN','ROLE_INSTRUCTOR']
                providers:
                    google:
                        failureUri: '/notFound'
                        api_key: ${google.apikey:314421498739-r0pbci40botjh0pmgb3pob5q0obr37r0.apps.googleusercontent.com}
                        api_secret: ${google.apisecret:eOc-t2xZoN19OoZono0K1uLc}
                        scope: 'https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email'
        cloudinary:
            apiKey: '675626252898869'
            apiSecret: 'GMzalj3XZ3aWsqrVuSGyQX7D8Bg'
            cloudName: 'vincoolns'
    controllers:
        upload:
            maxFileSize: 2097152
            maxRequestSize: 2097152


flyway:
    enabled: true
    locations: db/migration/
    baselineOnMigrate: true
spring:
  profiles:
